import type { Metadata } from "next";
import { Montserrat } from "next/font/google"
import "../globals.css";
import Nav from "@/components/nav/Nav";
import Providers from "@/components/Providers";
import PopupMessage from "@/components/shared/PopupMessage";
import SearchUsers from "@/components/shared/SearchUsers";
import SearchPosts from "@/components/shared/SearchPosts";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Matblogs auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${montserrat.className} bg-light`}
        >
          <SearchUsers />
          <SearchPosts />
          <PopupMessage />
          <Nav />
          <div className="main-padding-y">
            <div className="auth-container">
                {children}
            </div>
          </div>
        </body>
      </html>
    </Providers>
  );
}
